#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="SF Pro"

# when bar is on the right, everything is 90 deg off --
# so "height" is width, "padding_left" is at the top, etc
sketchybar --bar \
  position=right \
  height=35 \
  color=$BAR_COLOR \
  shadow=off \
  sticky=on \
  padding_right=3 \
  padding_left=29 \
  corner_radius=5 \
  margin=2 \
  blur_radius=20 \
  topmost=window

# y_offset=26

sketchybar --default \
  updates=when_shown \
  icon.font="$FONT:Bold:13.0" \
  icon.color=$ICON_COLOR \
  icon.padding_left=10 \
  icon.padding_right=10 \
  label.font="$FONT:Semibold:12.0" \
  label.color=$LABEL_COLOR \
  label.padding_left=2 \
  label.padding_right=2 \
  background.padding_right=4 \
  background.padding_left=4

source "$ITEM_DIR/spaces.sh"

sketchybar --update
