#!/bin/bash
#

# no color if arguments supplied (usually this is for -v)
if [ "$2" ]; then
   exec ssh $*
fi

hostspec=$1
# [[ $hostspec =~ ^(.*@)?([^.]*) ]] && host=${BASH_REMATCH[@]:2}
tmp=${hostspec/#*@/}; host=${tmp/.*}

# The default color which will be used when not connected to any host.
default_color="191919" 

case "$host" in
### Add special-cases for hosts here
    optimus)  host_color="768, 768, 11808";;
########################################################################

    *) 
    host_color=$(perl -e '
        $DARKNESS = 4;
        $host = $ARGV[0];
        while ($host =~ /(.)/g) { $seed += ord($1) };
        srand($seed);
        for (1..3) {
            $c = int(rand() * 256);
            if ($c > (256/$DARKNESS)) {
                $c = $c / $DARKNESS
            }
            push @colors, $c;
        };
        printf("%02x%02x%02x", @colors);
      ' $host)
    ;;
esac

trap cleanup 1 2 3 6

function cleanup() {
    set_color "$default_color"
    echo -ne "\033]0;\007"
}

function set_color() {
    color=$1
    echo -ne "\033]11;#${color}\007"
}

set_color "$host_color"

LOCAL_TERMCOLOR="$host_color" ssh -o SendEnv=LOCAL_TERMCOLOR $hostspec

cleanup
